# Generated by Django 5.0.9 on 2026-09-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ICE NOCK GLOBAL VENTURE', max_length=150)),
                ('phone', models.CharField(default='08033604514', max_length=30)),
                ('email', models.EmailField(default='abdulazizmohammedbello4@gmail.com', max_length=254)),
                ('receipt_footer', models.CharField(default='Thank you for your patronage! Goods sold in good condition are not returnable.', max_length=255)),
                ('currency_code', models.CharField(default='NGN', max_length=6)),
                ('currency_symbol', models.CharField(default='₦', max_length=4)),
                ('timezone_name', models.CharField(default='Africa/Lagos', max_length=64)),
                ('thermal_receipt_width_mm', models.PositiveSmallIntegerField(choices=[(58, '58mm'), (80, '80mm')], default=80)),
                ('low_stock_threshold_default', models.PositiveIntegerField(default=10, help_text="Used only for products that don't set their own minimum stock.")),
                ('discount_strategy', models.CharField(choices=[('HIGHEST', 'Highest Applicable Tier'), ('CUMULATIVE', 'Cumulative / Tier Decomposition'), ('BEST_VALID', 'Best Valid Discount (auto-pick best for customer)')], default='HIGHEST', max_length=12)),
                ('allow_manual_discount', models.BooleanField(default=True)),
                ('max_manual_discount_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
