# Generated by Django 5.0.9 on 2026-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='address',
            field=models.CharField(default='NO 34 ADO BAYERO PLAZA BAYAJIDDA STREET KADUNA', max_length=255),
        ),
    ]
