# Generated by Django 5.0.9 on 2026-09-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Carton 10+ tier'", max_length=100)),
                ('unit_type', models.CharField(choices=[('PACK', 'Pack'), ('CARTON', 'Carton'), ('BOTH', 'Both')], default='BOTH', max_length=6)),
                ('min_qty', models.PositiveIntegerField(default=1)),
                ('max_qty', models.PositiveIntegerField(blank=True, help_text='Leave blank for no upper limit.', null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 5 for 5%. Leave blank if using a fixed amount instead.', max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount per unit. Leave blank if using percentage.', max_digits=12, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['unit_type', 'min_qty'],
            },
        ),
    ]
